# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
